paths:
  /api/products:
    get:
      summary: obtener todos los Productos
      tags:
        - Productos
      responses:
        "200":
          description: devuelve los Productos
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#components/schemas/product'
        "500":
          description: "hubo un error"
  /api/products/{pid}:
    get:
      summary: obtener Uno de los Productos
      tags:
        - Productos
      parameters:
      - name: pid
        in: path
        required: true
        description: 'parametro de ruta para identificar el producto'
        schema:
          type: String
      responses:
        "200":
          description: devuelve un Productos segun su ID
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#components/schemas/product'
        "500":
          description: "hubo un error"
  /api/products/:
    post:
      summary: Crear producto
      tags:
        - Productos
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/createProduct"
      responses:
        "200":
          description: informa que se creo el producto con exito
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#components/schemas/product'
        "500":
          description: "hubo un error"
  /api/products/{putpid}:
    put:
      summary: Actualizar producto
      tags:
        - Productos
      parameters:
      - name: putpid
        in: path
        required: true
        description: 'parametro de ruta para identificar el producto'
        schema:
          type: String
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/updateProduct"
      responses:
        "200":
          description: devuelve un Productos segun su ID
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#components/schemas/product'
        "500":
          description: "hubo un error"
  /api/products/{deleteid}:
    delete:
      summary: Eliminar producto
      tags:
        - Productos
      parameters:
      - name: deleteid
        in: path
        required: true
        description: 'parametro de ruta para identificar el producto'
        schema:
          type: String
      responses:
        "200":
          description: devuelve un Productos segun su ID
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#components/schemas/product'
        "500":
          description: "hubo un error"
  

components:
  schemas:
    product:
      type: object
      properties:
        _id: 
          type: ObjectId
          description: id autogenerado por mongo
        title: 
          type: String
          description: nombre del Producto
        description: 
          type: String
          description: informacion del producto
        code: 
          type: Number
          description: codigo de referencia creado por usuario
        price: 
          type: Number
          description: precio total del producto
        status:
          type: Boolean
          description: nos informa si el producto esta disponible o no
        stock:
          type: Number
          description: cantidad de producto en el deposito
        category:
          type: String
          description: categoria del producto
        owner:
          type: String
          description: informacion del creador del producto
      example:
        _id: ObjectId("4562318420369")
        title: heladera
        description: philco medida standar rendimineto A+
        code: 123496
        price: 256.245
        status: true
        stock:  50
        category: 1 
        owner: admin/ isma@gmail.com

    createProduct:
      type: object
      properties:
        title: 
          type: String
          description: nombre del Producto
        description: 
          type: String
          description: informacion del producto
        code: 
          type: Number
          description: codigo de referencia creado por usuario
        price: 
          type: Number
          description: precio total del producto
        status:
          type: Boolean
          description: nos informa si el producto esta disponible o no
        stock:
          type: Number
          description: cantidad de producto en el deposito
        category:
          type: String
          description: categoria del producto
        owner:
          type: String
          description: informacion del creador del producto
      example:
        title: heladera
        description: philco medida standar rendimineto A+
        code: 123496
        price: 256.245
        status: true
        stock:  50
        category: 1 
        owner: admin/ isma@gmail.com
    
    updateProduct:
      type: object
      properties:
        title: 
          type: String
          description: nombre del Producto
        description: 
          type: String
          description: informacion del producto
        code: 
          type: Number
          description: codigo de referencia creado por usuario
        price: 
          type: Number
          description: precio total del producto
        status:
          type: Boolean
          description: nos informa si el producto esta disponible o no
        stock:
          type: Number
          description: cantidad de producto en el deposito
        category:
          type: String
          description: categoria del producto
      example:
        title: heladera
        description: philco medida standar rendimineto A+
        code: 123496
        price: 256.245
        status: true
        stock:  50
        category: 1 
        owner: admin